Add rules for capitialization of acronyms
Pocket/swift-style-guide pull request #2
Opened 2019-07-02 02:28 UTC by nzeltzer

Adds rules and examples for capitalization of acronyms consistent with Swift standard library.

2019-07-03 15:25 UTC, dskuza requested changes
I dig it - good addition! A few misspellings to fix. I would also add as a note that further information can be found [here](https://swift.org/documentation/api-design-guidelines/) under `General Conventions`.

2019-07-03 15:25 UTC, dskuza commented on README.markdown
> +// Second appearance goes lowercase, since it's at the beggining of a non-static constant name.
misspelling: `beggining`

2019-07-03 15:25 UTC, dskuza commented on README.markdown
> +// 'URL' goes at the beggining of the function name, use lowercase.
misspelling: `beggining`

2019-07-03 15:25 UTC, dskuza commented on README.markdown
> +// 'URL' goes at the beggining of a non-static constant name, use lowercase.
misspelling: `beggining`

2019-07-03 15:25 UTC, dskuza commented on README.markdown
> +// 'URL' isn't at the beggining of a non-static constant name, use UPPERCASE.
misspelling: `beggining`

2019-07-03 15:25 UTC, dskuza commented on README.markdown
> +// 'URL' goes at the beggining of a function name, it should go lowercase.
misspelling: `beggining`

2019-07-03 15:25 UTC, dskuza commented on README.markdown
> +// 'URL' goes at the beggining of a non-static constant name, it should go lowercase.
misspelling: `beggining`

2019-07-07 18:33 UTC, nzeltzer commented on README.markdown
> +// Second appearance goes lowercase, since it's at the beggining of a non-static constant name.
```suggestion
// Second appearance goes lowercase, since it's at the beginning of a non-static constant name.
```

2019-07-07 18:33 UTC, nzeltzer commented on README.markdown
> +// 'URL' goes at the beggining of the function name, use lowercase.
```suggestion
// 'URL' goes at the beginning of the function name, use lowercase.
```

2019-07-07 18:33 UTC, nzeltzer commented on README.markdown
> +// 'URL' goes at the beggining of a non-static constant name, use lowercase.
```suggestion
// 'URL' goes at the beginning of a non-static constant name, use lowercase.
```

2019-07-07 18:34 UTC, nzeltzer commented on README.markdown
> +// 'URL' isn't at the beggining of a non-static constant name, use UPPERCASE.
```suggestion
// 'URL' isn't at the beginning of a non-static constant name, use UPPERCASE.
```

2019-07-07 18:34 UTC, nzeltzer commented on README.markdown
> +// 'URL' goes at the beggining of a function name, it should go lowercase.
```suggestion
// 'URL' goes at the beginning of a function name, it should go lowercase.
```

2019-07-07 18:34 UTC, nzeltzer commented on README.markdown
> +// 'URL' goes at the beggining of a non-static constant name, it should go lowercase.
```suggestion
// 'URL' goes at the beginning of a non-static constant name, it should go lowercase.
```

2019-07-07 18:37 UTC, nzeltzer commented on README.markdown
> +[Acronyms](https://en.wikipedia.org/wiki/Acronym) must be capitalized such that all of its characters are uppercase, unless the acronym goes at the beginning of a name, in which case, all of its char
```suggestion
[Acronyms](https://en.wikipedia.org/wiki/Acronym) must be capitalized such that all of its characters are uppercase, unless the acronym goes at the beginning of a name, in which case, all of its characters will be lowercased. See, also, [Naming](#naming).
```

2019-07-09 15:10 UTC, dskuza approved these changes
:+1:

I keep forgetting suggestions are a thing, I sincerely apologize!

2019-07-09 15:13 UTC, merged